using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Lunil.Hosting.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class LuaClrBindingGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Lunil.Hosting.LuaClrGenerateBindingAttribute";
    private static readonly DiagnosticDescriptor Unsupported = new(
        "LUNILBIND001", "CLR member cannot be statically bound",
        "Symbol '{0}' cannot be statically bound: {1}", "Lunil.Binding",
        DiagnosticSeverity.Error, isEnabledByDefault: true);
    private static readonly DiagnosticDescriptor Duplicate = new(
        "LUNILBIND002", "Conflicting CLR binding request",
        "Type '{0}' has duplicate binding requests", "Lunil.Binding",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.CompilationProvider.Select(static (compilation, _) =>
            ReadRequests(compilation));
        context.RegisterSourceOutput(requests, static (output, value) => Emit(output, value));
    }

    private static ImmutableArray<Request> ReadRequests(Compilation compilation)
    {
        var result = ImmutableArray.CreateBuilder<Request>();
        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != AttributeName ||
                attribute.ConstructorArguments.Length == 0 ||
                attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
            {
                continue;
            }
            var names = ImmutableArray.CreateBuilder<string>();
            if (attribute.ConstructorArguments.Length > 1)
            {
                foreach (var value in attribute.ConstructorArguments[1].Values)
                {
                    if (value.Value is string name) names.Add(name);
                }
            }
            result.Add(new Request(type, names.ToImmutable(),
                attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation()));
        }
        return result.ToImmutable();
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Request> requests)
    {
        if (requests.IsDefaultOrEmpty) return;
        var unique = new Dictionary<string, Request>(StringComparer.Ordinal);
        foreach (var request in requests)
        {
            var key = TypeName(request.Type);
            if (unique.ContainsKey(key))
            {
                context.ReportDiagnostic(Diagnostic.Create(Duplicate, request.Location,
                    request.Type.ToDisplayString()));
                return;
            }
            unique.Add(key, request);
        }

        var source = new StringBuilder("""
// <auto-generated />
#nullable enable
namespace Lunil.Generated
{
    public sealed class LuaClrGeneratedBindings : global::Lunil.Hosting.ILuaClrBindingProvider
    {
        public void RegisterBindings(global::Lunil.Hosting.LuaClrBindingRegistry registry)
        {
            if (registry is null) throw new global::System.ArgumentNullException(nameof(registry));
""");
        var index = 0;
        foreach (var request in unique.Values.OrderBy(static item => item.Type.ToDisplayString(),
                     StringComparer.Ordinal))
        {
            if (!EmitType(context, request, index++, source)) return;
        }
        source.AppendLine("        }").AppendLine("    }").AppendLine("}");
        context.AddSource("Lunil.Generated.LuaClrGeneratedBindings.g.cs", source.ToString());
    }

    private static bool EmitType(
        SourceProductionContext context,
        Request request,
        int index,
        StringBuilder source)
    {
        var type = request.Type;
        if (type.IsRefLikeType || type.IsUnboundGenericType ||
            type.TypeArguments.Any(static argument => argument.TypeKind == TypeKind.TypeParameter))
        {
            return Fail(context, request, type, "the requested type is open or ref-like");
        }
        var constructors = (type.TypeKind == TypeKind.Delegate
                ? Enumerable.Empty<IMethodSymbol>()
                : type.InstanceConstructors)
            .Where(static item => item.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(Signature, StringComparer.Ordinal).ToArray();
        var names = new HashSet<string>(request.MemberNames, StringComparer.Ordinal);
        var members = AllMembers(type).Where(item => names.Contains(item.Name) &&
                item.DeclaredAccessibility == Accessibility.Public)
            .OrderBy(static item => item.Name, StringComparer.Ordinal)
            .ThenBy(Signature, StringComparer.Ordinal).ToArray();
        foreach (var name in names)
        {
            if (members.All(member => member.Name != name))
                return Fail(context, request, type, $"public member '{name}' was not found");
        }
        foreach (var constructor in constructors)
        {
            if (!Supported(constructor, out var reason))
                return Fail(context, request, constructor, reason);
        }
        foreach (var member in members)
        {
            if (!Supported(member, out var reason))
                return Fail(context, request, member, reason);
        }

        var tn = TypeName(type);
        source.Append("            var binding").Append(index)
            .Append(" = new global::Lunil.Hosting.LuaClrTypeBinding(typeof(").Append(tn)
            .AppendLine("),").AppendLine("                new global::Lunil.Hosting.LuaClrConstructorBinding[]")
            .AppendLine("                {");
        foreach (var constructor in constructors) EmitConstructor(source, tn, constructor);
        source.AppendLine("                },").AppendLine("                new global::Lunil.Hosting.LuaClrMemberBinding[]")
            .AppendLine("                {");
        foreach (var member in members) EmitMember(source, tn, member);
        source.Append("                }");
        if (type.TypeKind == TypeKind.Delegate && type.DelegateInvokeMethod is { } invoke)
        {
            if (!Supported(invoke, out var reason))
                return Fail(context, request, invoke, reason);
            source.AppendLine(",").Append("                callback => new ").Append(tn).Append('(');
            EmitDelegate(source, invoke);
            source.AppendLine("),").Append("                typeof(")
                .Append(TypeName(invoke.ReturnType)).Append(')');
        }
        source.AppendLine(");").Append("            registry.Register(binding").Append(index)
            .AppendLine(");");
        if (type.IsGenericType &&
            !SymbolEqualityComparer.Default.Equals(type, type.OriginalDefinition))
        {
            source.Append("            registry.RegisterClosedGeneric(")
                .Append(Literal(MetadataDefinitionName(type.OriginalDefinition))).Append(", new string[] { ");
            for (var i = 0; i < type.TypeArguments.Length; i++)
            {
                if (i > 0) source.Append(", ");
                source.Append(Literal(MetadataTypeName(type.TypeArguments[i])));
            }
            source.Append(" }, binding").Append(index).AppendLine(");");
        }
        return true;
    }

    private static void EmitConstructor(StringBuilder source, string type, IMethodSymbol method)
    {
        source.AppendLine("                    new global::Lunil.Hosting.LuaClrConstructorBinding(")
            .Append("                        ");
        EmitParameters(source, method.Parameters);
        source.AppendLine(",").AppendLine("                        static arguments =>")
            .AppendLine("                        {");
        EmitLocals(source, method.Parameters);
        source.Append("                            return new ").Append(type).Append('(');
        EmitCallArguments(source, method.Parameters);
        source.AppendLine(");").AppendLine("                        }),");
    }

    private static void EmitMember(StringBuilder source, string type, ISymbol member)
    {
        switch (member)
        {
            case IMethodSymbol method: EmitMethod(source, type, method); break;
            case IPropertySymbol property: EmitProperty(source, type, property); break;
            case IFieldSymbol field: EmitField(source, type, field); break;
            case IEventSymbol @event: EmitEvent(source, type, @event); break;
        }
    }

    private static void EmitMethod(StringBuilder source, string type, IMethodSymbol method)
    {
        var kind = method.Name.StartsWith("op_", StringComparison.Ordinal) ? "Operator" : "Method";
        source.AppendLine("                    new global::Lunil.Hosting.LuaClrMemberBinding(")
            .Append("                        ").Append(Literal(method.Name))
            .Append(", global::Lunil.Hosting.LuaClrMemberKind.").Append(kind).Append(", ")
            .Append(Bool(method.IsStatic)).AppendLine(", false, false,")
            .Append("                        ");
        EmitParameters(source, method.Parameters);
        source.Append(", typeof(").Append(TypeName(method.ReturnType)).AppendLine("),")
            .AppendLine("                        static (target, arguments) =>")
            .AppendLine("                        {");
        EmitLocals(source, method.Parameters);
        source.Append("                            ");
        if (!method.ReturnsVoid) source.Append("var result = ");
        source.Append(Receiver(type, method.IsStatic)).Append('.').Append(method.Name).Append('(');
        EmitCallArguments(source, method.Parameters);
        source.AppendLine(");");
        for (var i = 0; i < method.Parameters.Length; i++)
        {
            if (method.Parameters[i].RefKind is RefKind.Ref or RefKind.Out)
                source.Append("                            arguments[").Append(i).Append("] = arg")
                    .Append(i).AppendLine(";");
        }
        source.Append("                            return ")
            .AppendLine(method.ReturnsVoid ? "null;" : "result;")
            .AppendLine("                        }),");
    }

    private static void EmitProperty(StringBuilder source, string type, IPropertySymbol property)
    {
        var read = property.GetMethod?.DeclaredAccessibility == Accessibility.Public;
        var write = property.SetMethod?.DeclaredAccessibility == Accessibility.Public;
        var receiver = Receiver(type, property.IsStatic);
        var access = property.IsIndexer
            ? receiver + "[" + string.Join(", ", property.Parameters.Select((_, i) => "arg" + i)) + "]"
            : receiver + "." + property.Name;
        source.AppendLine("                    new global::Lunil.Hosting.LuaClrMemberBinding(")
            .Append("                        ").Append(Literal(property.Name))
            .Append(", global::Lunil.Hosting.LuaClrMemberKind.")
            .Append(property.IsIndexer ? "Indexer" : "Property").Append(", ")
            .Append(Bool(property.IsStatic)).Append(", ").Append(Bool(read)).Append(", ")
            .Append(Bool(write)).AppendLine(",").Append("                        ");
        EmitParameters(source, property.Parameters);
        source.Append(", typeof(").Append(TypeName(property.Type)).AppendLine("),")
            .AppendLine("                        static (target, arguments) =>")
            .AppendLine("                        {");
        EmitLocals(source, property.Parameters);
        if (read && write)
        {
            source.Append("                            if (arguments.Length == ")
                .Append(property.Parameters.Length).AppendLine(")")
                .AppendLine("                            {")
                .Append("                                return ").Append(access).AppendLine(";")
                .AppendLine("                            }");
        }
        if (write)
        {
            source.Append("                            ").Append(access).Append(" = (")
                .Append(TypeName(property.Type)).Append(")arguments[")
                .Append(property.Parameters.Length).AppendLine("]!;")
                .AppendLine("                            return null;");
        }
        else
        {
            source.Append("                            return ").Append(access).AppendLine(";");
        }
        source.AppendLine("                        }),");
    }

    private static void EmitField(StringBuilder source, string type, IFieldSymbol field)
    {
        var write = !field.IsReadOnly && !field.IsConst;
        var access = Receiver(type, field.IsStatic) + "." + field.Name;
        source.AppendLine("                    new global::Lunil.Hosting.LuaClrMemberBinding(")
            .Append("                        ").Append(Literal(field.Name))
            .Append(", global::Lunil.Hosting.LuaClrMemberKind.Field, ")
            .Append(Bool(field.IsStatic)).Append(", true, ").Append(Bool(write))
            .Append(", [], typeof(").Append(TypeName(field.Type)).AppendLine("),")
            .AppendLine("                        static (target, arguments) =>")
            .AppendLine("                        {");
        if (write)
        {
            source.AppendLine("                            if (arguments.Length == 0)")
                .AppendLine("                            {").Append("                                return ")
                .Append(access).AppendLine(";").AppendLine("                            }")
                .Append("                            ").Append(access).Append(" = (")
                .Append(TypeName(field.Type)).AppendLine(")arguments[0]!;")
                .AppendLine("                            return null;");
        }
        else source.Append("                            return ").Append(access).AppendLine(";");
        source.AppendLine("                        }),");
    }

    private static void EmitEvent(StringBuilder source, string type, IEventSymbol @event)
    {
        var access = Receiver(type, @event.IsStatic) + "." + @event.Name;
        source.AppendLine("                    new global::Lunil.Hosting.LuaClrMemberBinding(")
            .Append("                        ").Append(Literal(@event.Name))
            .Append(", global::Lunil.Hosting.LuaClrMemberKind.Event, ")
            .Append(Bool(@event.IsStatic)).AppendLine(", false, false,")
            .Append("                        new global::Lunil.Hosting.LuaClrParameterBinding[] { new global::Lunil.Hosting.LuaClrParameterBinding(\"handler\", typeof(")
            .Append(TypeName(@event.Type)).AppendLine(")) }, typeof(void),")
            .AppendLine("                        static (target, arguments) =>")
            .AppendLine("                        {").Append("                            var handler = (")
            .Append(TypeName(@event.Type)).AppendLine(")arguments[0]!;")
            .AppendLine("                            if ((bool)arguments[1]!)")
            .Append("                                ").Append(access).AppendLine(" += handler;")
            .AppendLine("                            else").Append("                                ")
            .Append(access).AppendLine(" -= handler;").AppendLine("                            return null;")
            .AppendLine("                        }),");
    }

    private static void EmitDelegate(StringBuilder source, IMethodSymbol invoke)
    {
        source.Append('(');
        for (var i = 0; i < invoke.Parameters.Length; i++)
        {
            if (i > 0) source.Append(", ");
            source.Append("arg").Append(i);
        }
        source.Append(") => ");
        if (invoke.ReturnsVoid) source.Append("{ callback(new object?[] { ");
        else source.Append('(').Append(TypeName(invoke.ReturnType))
            .Append(")callback(new object?[] { ");
        for (var i = 0; i < invoke.Parameters.Length; i++)
        {
            if (i > 0) source.Append(", ");
            source.Append("arg").Append(i);
        }
        source.Append(invoke.ReturnsVoid ? " }); }" : " })!");
    }

    private static void EmitParameters(
        StringBuilder source,
        ImmutableArray<IParameterSymbol> parameters)
    {
        if (parameters.Length == 0)
        {
            source.Append("global::System.Array.Empty<global::Lunil.Hosting.LuaClrParameterBinding>()");
            return;
        }
        source.Append("new global::Lunil.Hosting.LuaClrParameterBinding[] { ");
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0) source.Append(", ");
            var p = parameters[i];
            source.Append("new global::Lunil.Hosting.LuaClrParameterBinding(")
                .Append(Literal(p.Name)).Append(", typeof(").Append(TypeName(p.Type))
                .Append("), ").Append(Bool(p.RefKind != RefKind.None)).Append(", ")
                .Append(Bool(p.RefKind == RefKind.Out)).Append(", ")
                .Append(Bool(p.HasExplicitDefaultValue)).Append(", ")
                .Append(DefaultValue(p)).Append(')');
        }
        source.Append(" }");
    }

    private static void EmitLocals(
        StringBuilder source,
        ImmutableArray<IParameterSymbol> parameters)
    {
        for (var i = 0; i < parameters.Length; i++)
        {
            var p = parameters[i];
            source.Append("                            ").Append(TypeName(p.Type)).Append(" arg")
                .Append(i).Append(" = ");
            if (p.RefKind == RefKind.Out) source.AppendLine("default!;");
            else source.Append('(').Append(TypeName(p.Type)).Append(")arguments[")
                .Append(i).AppendLine("]!;");
        }
    }

    private static void EmitCallArguments(
        StringBuilder source,
        ImmutableArray<IParameterSymbol> parameters)
    {
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0) source.Append(", ");
            source.Append(parameters[i].RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In => "in ",
                _ => string.Empty,
            }).Append("arg").Append(i);
        }
    }

    private static bool Supported(ISymbol symbol, out string reason)
    {
        ImmutableArray<IParameterSymbol> parameters;
        switch (symbol)
        {
            case IMethodSymbol method when method.MethodKind is MethodKind.Constructor or MethodKind.Ordinary or MethodKind.DelegateInvoke:
                if (method.IsGenericMethod || method.ReturnsByRef || method.ReturnsByRefReadonly ||
                    method.ReturnType.IsRefLikeType)
                {
                    reason = "generic, by-ref-return, or ref-like-return methods are unsupported";
                    return false;
                }
                parameters = method.Parameters;
                break;
            case IPropertySymbol property when !property.ReturnsByRef &&
                                                   !property.ReturnsByRefReadonly &&
                                                   !property.Type.IsRefLikeType:
                parameters = property.Parameters;
                break;
            case IFieldSymbol field when !field.Type.IsRefLikeType:
            case IEventSymbol { Type.TypeKind: TypeKind.Delegate }:
                reason = string.Empty;
                return true;
            default:
                reason = "the symbol kind or ref-like shape is unsupported";
                return false;
        }
        foreach (var parameter in parameters)
        {
            if (parameter.Type.IsRefLikeType || parameter.Type.TypeKind is TypeKind.Pointer or TypeKind.FunctionPointer ||
                parameter.RefKind == RefKind.RefReadOnlyParameter)
            {
                reason = $"parameter '{parameter.Name}' is pointer, ref-like, or ref-readonly";
                return false;
            }
        }
        reason = string.Empty;
        return true;
    }

    private static IEnumerable<ISymbol> AllMembers(INamedTypeSymbol type)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        for (var current = type; current is not null; current = current.BaseType)
        {
            foreach (var member in current.GetMembers())
            {
                var key = member.Kind + "|" + member.Name + "|" + Signature(member);
                if (seen.Add(key)) yield return member;
            }
        }
    }

    private static string Signature(ISymbol symbol) => symbol switch
    {
        IMethodSymbol method => string.Join("|", method.Parameters.Select(static p =>
            p.Type.ToDisplayString() + ":" + p.RefKind)),
        IPropertySymbol property => string.Join("|", property.Parameters.Select(static p =>
            p.Type.ToDisplayString())),
        IFieldSymbol field => field.Type.ToDisplayString(),
        IEventSymbol @event => @event.Type.ToDisplayString(),
        _ => string.Empty,
    };

    private static bool Fail(
        SourceProductionContext context,
        Request request,
        ISymbol symbol,
        string reason)
    {
        context.ReportDiagnostic(Diagnostic.Create(Unsupported,
            symbol.Locations.FirstOrDefault() ?? request.Location,
            symbol.ToDisplayString(), reason));
        return false;
    }

    private static string Receiver(string type, bool isStatic) =>
        isStatic ? type : "((" + type + ")target!)";

    private static string TypeName(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string MetadataDefinitionName(INamedTypeSymbol type)
    {
        var prefix = type.ContainingType is not null
            ? MetadataDefinitionName(type.ContainingType) + "+"
            : type.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : type.ContainingNamespace.ToDisplayString() + ".";
        return prefix + type.MetadataName;
    }

    private static string MetadataTypeName(ITypeSymbol type) => type switch
    {
        IArrayTypeSymbol array => MetadataTypeName(array.ElementType) + "[]",
        INamedTypeSymbol named when !named.IsGenericType => MetadataDefinitionName(named),
        _ => type.ToDisplayString().Replace("global::", string.Empty),
    };

    private static string DefaultValue(IParameterSymbol parameter)
    {
        if (!parameter.HasExplicitDefaultValue || parameter.ExplicitDefaultValue is null) return "null";
        return parameter.ExplicitDefaultValue switch
        {
            string text => Literal(text),
            char value => SymbolDisplay.FormatLiteral(value, quote: true),
            bool value => Bool(value),
            float value => value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "F",
            double value => value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "D",
            _ => Convert.ToString(parameter.ExplicitDefaultValue,
                System.Globalization.CultureInfo.InvariantCulture) ?? "null",
        };
    }

    private static string Literal(string value) => SymbolDisplay.FormatLiteral(value, quote: true);
    private static string Bool(bool value) => value ? "true" : "false";

    private sealed class Request
    {
        public Request(
            INamedTypeSymbol type,
            ImmutableArray<string> memberNames,
            Location? location)
        {
            Type = type;
            MemberNames = memberNames;
            Location = location;
        }

        public INamedTypeSymbol Type { get; }
        public ImmutableArray<string> MemberNames { get; }
        public Location? Location { get; }
    }
}
