using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Lunil.StandardLibrary.Generators;

/// <summary>
/// Emits strongly typed native invokers for <c>[assembly: LuaFfiGenerateBinding]</c>
/// requests. Each declared (library, symbol, signature) tuple becomes a compile-time
/// delegate type plus an address-resolved invoker, so bound symbols marshal without
/// runtime delegate generation and work on AOT and trimmed runtimes.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class LuaFfiBindingGenerator : IIncrementalGenerator
{
    private const string AttributeName = "Lunil.StandardLibrary.LuaFfiGenerateBindingAttribute";

    private static readonly DiagnosticDescriptor InvalidRequest = new(
        "LUNILFFI001", "Native binding request is invalid",
        "Native binding '{0}!{1}' cannot be generated: {2}", "Lunil.FfiBinding",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateRequest = new(
        "LUNILFFI002", "Conflicting native binding request",
        "Native symbol '{0}!{1}' has duplicate binding requests", "Lunil.FfiBinding",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.CompilationProvider.Select(static (compilation, _) =>
            ReadRequests(compilation));
        context.RegisterSourceOutput(requests, static (output, value) => Emit(output, value));
    }

    private static ImmutableArray<Request> ReadRequests(Compilation compilation)
    {
        var result = ImmutableArray.CreateBuilder<Request>();
        foreach (var attribute in compilation.Assembly.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != AttributeName ||
                attribute.ConstructorArguments.Length < 3)
            {
                continue;
            }

            var library = attribute.ConstructorArguments[0].Value as string;
            var symbol = attribute.ConstructorArguments[1].Value as string;
            var signature = attribute.ConstructorArguments[2].Value as string;
            var convention = attribute.ConstructorArguments.Length > 3 &&
                attribute.ConstructorArguments[3].Value is string requested &&
                !string.IsNullOrEmpty(requested)
                    ? requested
                    : "platform";
            result.Add(new Request(
                library,
                symbol,
                signature,
                convention,
                attribute.ApplicationSyntaxReference?.GetSyntax().GetLocation()));
        }

        return result.ToImmutable();
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Request> requests)
    {
        if (requests.IsDefaultOrEmpty)
        {
            return;
        }

        var bySymbol = new Dictionary<(string Library, string Symbol), Validated>(
            new LibrarySymbolComparer());
        foreach (var request in requests)
        {
            var key = (request.Library ?? string.Empty, request.Symbol ?? string.Empty);
            if (bySymbol.ContainsKey(key))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateRequest,
                    request.Location,
                    key.Item1,
                    key.Item2));
                continue;
            }

            var validated = Validate(request);
            if (validated.Error is not null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidRequest,
                    request.Location,
                    key.Item1,
                    key.Item2,
                    validated.Error));
                continue;
            }

            bySymbol[key] = validated;
        }

        if (bySymbol.Count == 0)
        {
            return;
        }

        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("namespace Lunil.Generated");
        code.AppendLine("{");
        code.AppendLine("    /// <summary>Registers the compile-time generated native FFI bindings.</summary>");
        code.AppendLine("    public sealed class LuaFfiGeneratedBindings : " +
            "global::Lunil.StandardLibrary.ILuaFfiBindingProvider");
        code.AppendLine("    {");
        code.AppendLine("        /// <summary>Registers the generated bindings into the registry.</summary>");
        code.AppendLine("        public void RegisterBindings(" +
            "global::Lunil.StandardLibrary.LuaFfiBindingRegistry registry)");
        code.AppendLine("        {");
        foreach (var entry in bySymbol.OrderBy(
                     static entry => entry.Key.Item1,
                     StringComparer.Ordinal).ThenBy(
                     static entry => entry.Key.Item2,
                     StringComparer.Ordinal))
        {
            var library = Literal(entry.Key.Item1);
            var symbol = Literal(entry.Key.Item2);
            var signature = Literal(entry.Value.SignatureText);
            var convention = entry.Value.Convention;
            code.AppendLine($"            registry.Register(new global::Lunil.StandardLibrary.LuaFfiNativeBinding(");
            code.AppendLine($"                {library},");
            code.AppendLine($"                {symbol},");
            code.AppendLine($"                global::Lunil.StandardLibrary.LuaFfiSignature.Parse({signature}, " +
                $"global::Lunil.StandardLibrary.LuaFfiCallingConvention.{convention.RuntimeName}),");
            code.AppendLine($"                {entry.Value.InvokerName}));");
        }

        code.AppendLine("        }");
        code.AppendLine();
        foreach (var entry in bySymbol.OrderBy(
                     static entry => entry.Key.Item1,
                     StringComparer.Ordinal).ThenBy(
                     static entry => entry.Key.Item2,
                     StringComparer.Ordinal))
        {
            var value = entry.Value;
            code.AppendLine($"        private static object? {value.InvokerName}(" +
                "global::System.IntPtr address, global::System.ReadOnlySpan<object?> arguments)");
            code.AppendLine("        {");
            code.AppendLine("            var native = global::System.Runtime.InteropServices.Marshal" +
                $".GetDelegateForFunctionPointer<{value.DelegateName}>(address);");
            var call = new StringBuilder("native(");
            for (var index = 0; index < value.ParameterTypes.Length; index++)
            {
                if (index > 0)
                {
                    call.Append(", ");
                }

                call.Append('(').Append(ClrTypeName(value.ParameterTypes[index]))
                    .Append(")arguments[").Append(index).Append("]!");
            }

            call.Append(')');
            code.AppendLine(value.ReturnType == NativeType.Void
                ? $"            {call};"
                : $"            return {call};");
            if (value.ReturnType == NativeType.Void)
            {
                code.AppendLine("            return null;");
            }

            code.AppendLine("        }");
            code.AppendLine();
            code.AppendLine("        [global::System.Runtime.InteropServices" +
                $".UnmanagedFunctionPointerAttribute(global::System.Runtime.InteropServices" +
                $".CallingConvention.{value.Convention.MarshalName})]");
            code.Append("        private delegate ").Append(ClrTypeName(value.ReturnType))
                .Append(' ').Append(value.DelegateName).Append('(');
            for (var index = 0; index < value.ParameterTypes.Length; index++)
            {
                if (index > 0)
                {
                    code.Append(", ");
                }

                code.Append(ClrTypeName(value.ParameterTypes[index]))
                    .Append(" arg").Append(index);
            }

            code.AppendLine(");");
            code.AppendLine();
        }

        code.AppendLine("    }");
        code.AppendLine("}");
        context.AddSource("LuaFfiGeneratedBindings.g.cs", code.ToString());
    }

    private static Validated Validate(Request request)
    {
        if (string.IsNullOrWhiteSpace(request.Library) || request.Library.Contains('\0'))
        {
            return new Validated("the library name is required and cannot contain NUL characters.");
        }

        if (string.IsNullOrWhiteSpace(request.Symbol) || request.Symbol.Contains('\0'))
        {
            return new Validated("the symbol name is required and cannot contain NUL characters.");
        }

        var convention = request.CallingConvention switch
        {
            "platform" => new Convention("PlatformDefault", "Winapi"),
            "cdecl" => new Convention("Cdecl", "Cdecl"),
            "stdcall" => new Convention("Stdcall", "StdCall"),
            _ => default,
        };
        if (convention.RuntimeName is null)
        {
            return new Validated(
                $"the calling convention '{request.CallingConvention}' is not one of platform, cdecl, stdcall.");
        }

        if (string.IsNullOrWhiteSpace(request.Signature))
        {
            return new Validated("a native signature is required.");
        }

        var signatureText = request.Signature!.Trim();

        var open = signatureText.IndexOf('(');
        var close = signatureText.LastIndexOf(')');
        if (open <= 0 || close != signatureText.Length - 1 || close < open)
        {
            return new Validated("the signature must have the form returnType(parameterTypes).");
        }

        if (!TryParseType(signatureText.Substring(0, open), out var returnType, out var returnError))
        {
            return new Validated(returnError);
        }

        var parameterText = signatureText.Substring(open + 1, close - open - 1).Trim();
        var parameters = ImmutableArray<NativeType>.Empty;
        if (parameterText.Length != 0)
        {
            var builder = ImmutableArray.CreateBuilder<NativeType>();
            foreach (var part in parameterText.Split(','))
            {
                if (!TryParseType(part.Trim(), out var parameter, out var parameterError))
                {
                    return new Validated(parameterError);
                }

                builder.Add(parameter);
            }

            parameters = builder.ToImmutable();
        }

        var suffix = new StringBuilder();
        foreach (var type in parameters)
        {
            suffix.Append('_').Append(TypeSuffix(type));
        }

        var identifier = SanitizeIdentifier(request.Library!) + "_" +
            SanitizeIdentifier(request.Symbol!);
        return new Validated(
            signatureText,
            convention,
            returnType,
            parameters,
            "Invoke_" + identifier,
            "Delegate_" + identifier + suffix);
    }

    /// <summary> Parses the same alias table as <c>LuaFfiSignature.ParseType</c>; the
    /// runtime re-parses the declaration, so both sides must agree on every alias. </summary>
    private static bool TryParseType(string text, out NativeType type, out string error)
    {
        var normalized = text.Trim().ToLowerInvariant()
            .Replace(" ", string.Empty)
            .Replace("const", string.Empty);
        normalized = normalized switch
        {
            "void*" or "ptr" or "pointer" => "pointer",
            "char*" or "constchar*" or "cstring" or "utf8" or "utf8string" => "cstring",
            "_bool" or "bool" or "bool8" => "bool",
            "signedchar" or "int8" or "int8_t" or "i8" => "i8",
            "unsignedchar" or "uint8" or "uint8_t" or "u8" => "u8",
            "short" or "int16" or "int16_t" or "i16" => "i16",
            "unsignedshort" or "uint16" or "uint16_t" or "u16" => "u16",
            "int" or "int32" or "int32_t" or "i32" => "i32",
            "unsigned" or "unsignedint" or "uint32" or "uint32_t" or "u32" => "u32",
            "longlong" or "int64" or "int64_t" or "i64" => "i64",
            "unsignedlonglong" or "uint64" or "uint64_t" or "u64" => "u64",
            "intptr" or "intptr_t" or "isize" => "isize",
            "uintptr" or "uintptr_t" or "size_t" or "usize" => "usize",
            "float" or "f32" => "f32",
            "double" or "f64" => "f64",
            _ => normalized,
        };

        type = normalized switch
        {
            "void" => NativeType.Void,
            "bool" => NativeType.Boolean,
            "i8" => NativeType.Int8,
            "u8" => NativeType.UInt8,
            "i16" => NativeType.Int16,
            "u16" => NativeType.UInt16,
            "i32" => NativeType.Int32,
            "u32" => NativeType.UInt32,
            "i64" => NativeType.Int64,
            "u64" => NativeType.UInt64,
            "isize" => NativeType.IntPtr,
            "usize" => NativeType.UIntPtr,
            "f32" => NativeType.Float,
            "f64" => NativeType.Double,
            "cstring" => NativeType.Utf8String,
            "pointer" => NativeType.Pointer,
            _ => NativeType.Void,
        };
        if (normalized is not ("void" or "bool" or "i8" or "u8" or "i16" or "u16" or "i32" or
            "u32" or "i64" or "u64" or "isize" or "usize" or "f32" or "f64" or "cstring" or
            "pointer"))
        {
            error = $"native type '{text}' is not supported.";
            return false;
        }

        error = string.Empty;
        return true;
    }

    /// <summary>Mirrors the CLR boxing produced by LuaFfiContext.ConvertArgument.</summary>
    private static string ClrTypeName(NativeType type) => type switch
    {
        NativeType.Void => "void",
        NativeType.Boolean or NativeType.UInt8 => "byte",
        NativeType.Int8 => "sbyte",
        NativeType.Int16 => "short",
        NativeType.UInt16 => "ushort",
        NativeType.Int32 => "int",
        NativeType.UInt32 => "uint",
        NativeType.Int64 => "long",
        NativeType.UInt64 => "ulong",
        NativeType.IntPtr or NativeType.Pointer or NativeType.Utf8String =>
            "global::System.IntPtr",
        NativeType.UIntPtr => "global::System.UIntPtr",
        NativeType.Float => "float",
        NativeType.Double => "double",
        _ => throw new ArgumentOutOfRangeException(nameof(type)),
    };

    private static string TypeSuffix(NativeType type) => type switch
    {
        NativeType.Boolean => "b8",
        NativeType.Int8 => "i8",
        NativeType.UInt8 => "u8",
        NativeType.Int16 => "i16",
        NativeType.UInt16 => "u16",
        NativeType.Int32 => "i32",
        NativeType.UInt32 => "u32",
        NativeType.Int64 => "i64",
        NativeType.UInt64 => "u64",
        NativeType.IntPtr => "isize",
        NativeType.UIntPtr => "usize",
        NativeType.Float => "f32",
        NativeType.Double => "f64",
        NativeType.Utf8String => "cstring",
        NativeType.Pointer => "ptr",
        _ => throw new ArgumentOutOfRangeException(nameof(type)),
    };

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        }

        return builder.Length == 0 ? "symbol" : builder.ToString();
    }

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    private enum NativeType
    {
        Void,
        Boolean,
        Int8,
        UInt8,
        Int16,
        UInt16,
        Int32,
        UInt32,
        Int64,
        UInt64,
        IntPtr,
        UIntPtr,
        Float,
        Double,
        Utf8String,
        Pointer,
    }

    private readonly struct Convention
    {
        public Convention(string runtimeName, string marshalName)
        {
            RuntimeName = runtimeName;
            MarshalName = marshalName;
        }

        public string RuntimeName { get; }

        public string MarshalName { get; }
    }

    private sealed class Validated
    {
        public Validated(
            string signatureText,
            Convention convention,
            NativeType returnType,
            ImmutableArray<NativeType> parameterTypes,
            string invokerName,
            string delegateName)
        {
            SignatureText = signatureText;
            Convention = convention;
            ReturnType = returnType;
            ParameterTypes = parameterTypes;
            InvokerName = invokerName;
            DelegateName = delegateName;
        }

        public Validated(string error)
            : this(
                string.Empty,
                default,
                NativeType.Void,
                ImmutableArray<NativeType>.Empty,
                string.Empty,
                string.Empty)
        {
            Error = error;
        }

        public string? Error { get; }

        public string SignatureText { get; }

        public Convention Convention { get; }

        public NativeType ReturnType { get; }

        public ImmutableArray<NativeType> ParameterTypes { get; }

        public string InvokerName { get; }

        public string DelegateName { get; }
    }

    private sealed class Request
    {
        public Request(
            string? library,
            string? symbol,
            string? signature,
            string callingConvention,
            Location? location)
        {
            Library = library;
            Symbol = symbol;
            Signature = signature;
            CallingConvention = callingConvention;
            Location = location;
        }

        public string? Library { get; }

        public string? Symbol { get; }

        public string? Signature { get; }

        public string CallingConvention { get; }

        public Location? Location { get; }
    }

    private sealed class LibrarySymbolComparer : IEqualityComparer<(string Library, string Symbol)>
    {
        public bool Equals((string Library, string Symbol) x, (string Library, string Symbol) y) =>
            string.Equals(x.Library, y.Library, StringComparison.Ordinal) &&
            string.Equals(x.Symbol, y.Symbol, StringComparison.Ordinal);

        public int GetHashCode((string Library, string Symbol) obj) =>
            StringComparer.Ordinal.GetHashCode(obj.Library) * 397 ^
            StringComparer.Ordinal.GetHashCode(obj.Symbol);
    }
}
