using System.Globalization;
using Microsoft.CodeAnalysis;

namespace Lunil.IR.Generators;

[Generator]
public sealed class Lua53OpcodeTableGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor InvalidOpcodeLayout = new(
        "LUNILGEN001",
        "Invalid Lua 5.3 opcode layout",
        "Lua53Opcode values must be contiguous from zero and fit the six-bit opcode field; " +
        "expected {0}, found {1} on '{2}'",
        "Lunil.Build",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var opcode = context.Compilation.GetTypeByMetadataName("Lunil.IR.Lua53.Lua53Opcode");
        if (opcode is null || opcode.TypeKind != TypeKind.Enum)
        {
            return;
        }

        var values = opcode.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .Select(static field => (Name: field.Name, Value: Convert.ToInt32(
                field.ConstantValue,
                CultureInfo.InvariantCulture)))
            .OrderBy(static item => item.Value)
            .ToArray();
        if (values.Length == 0)
        {
            return;
        }

        for (var index = 0; index < values.Length; index++)
        {
            if (values[index].Value == index && values[index].Value <= 0x3f)
            {
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                InvalidOpcodeLayout,
                Location.None,
                index,
                values[index].Value,
                values[index].Name));
            return;
        }

        var cases = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua53Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        var source = $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua53;

            internal static class Lua53GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};

                internal static bool IsDefined(Lua53Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }

                internal static string GetName(Lua53Opcode opcode) => (int)opcode switch
                {
                    {{cases}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }

            internal static class Lua53GeneratedInstructionCodec
            {
                internal const int MaximumA = 0xff;
                internal const int MaximumB = 0x1ff;
                internal const int MaximumC = 0x1ff;
                internal const int MaximumBx = 0x3ffff;
                internal const int MaximumAx = 0x3ffffff;
                internal const int SignedBxOffset = MaximumBx >> 1;

                internal static Lua53Opcode DecodeOpcode(uint raw) =>
                    (Lua53Opcode)(raw & 0x3f);

                internal static int DecodeA(uint raw) => (int)((raw >> 6) & MaximumA);

                internal static int DecodeC(uint raw) => (int)((raw >> 14) & MaximumC);

                internal static int DecodeB(uint raw) => (int)((raw >> 23) & MaximumB);

                internal static int DecodeBx(uint raw) => (int)((raw >> 14) & MaximumBx);

                internal static int DecodeAx(uint raw) => (int)((raw >> 6) & MaximumAx);

                internal static uint EncodeAbc(Lua53Opcode opcode, int a, int b, int c) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)c << 14) | ((uint)b << 23);

                internal static uint EncodeABx(Lua53Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)bx << 14);

                internal static uint EncodeAx(Lua53Opcode opcode, int ax) =>
                    (uint)opcode | ((uint)ax << 6);
            }
            """;
        context.AddSource("Lua53GeneratedOpcodeTable.g.cs", source);
    }
}

[Generator]
public sealed class Lua51OpcodeTableGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        var opcode = context.Compilation.GetTypeByMetadataName("Lunil.IR.Lua51.Lua51Opcode");
        if (opcode is null || opcode.TypeKind != TypeKind.Enum)
            return;
        var values = opcode.GetMembers().OfType<IFieldSymbol>().Where(static field => field.HasConstantValue)
            .Select(static field => (Name: field.Name, Value: Convert.ToInt32(field.ConstantValue, CultureInfo.InvariantCulture)))
            .OrderBy(static item => item.Value).ToArray();
        if (values.Length == 0)
            return;
        for (var index = 0; index < values.Length; index++)
        {
            if (values[index].Value != index || values[index].Value > 0x3f)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor("LUNILGEN003", "Invalid Lua 5.1 opcode layout",
                        "Lua51Opcode values must be contiguous from zero", "Lunil.Build",
                        DiagnosticSeverity.Error, true), Location.None));
                return;
            }
        }
        var names = string.Join(",\n            ", values.Select(static item => $"{item.Value} => nameof(Lua51Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        context.AddSource("Lua51GeneratedOpcodeTable.g.cs", $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua51;
            internal static class Lua51GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};
                internal static bool IsDefined(Lua51Opcode opcode) { var value = (int)opcode; return {{defined}}; }
                internal static string GetName(Lua51Opcode opcode) => (int)opcode switch
                {
                    {{names}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }
            internal static class Lua51GeneratedInstructionCodec
            {
                internal const int MaximumA = 0xff;
                internal const int MaximumB = 0x1ff;
                internal const int MaximumC = 0x1ff;
                internal const int MaximumBx = 0x3ffff;
                internal const int SignedBxOffset = MaximumBx >> 1;
                internal static Lua51Opcode DecodeOpcode(uint raw) => (Lua51Opcode)(raw & 0x3f);
                internal static int DecodeA(uint raw) => (int)((raw >> 6) & MaximumA);
                internal static int DecodeC(uint raw) => (int)((raw >> 14) & MaximumC);
                internal static int DecodeB(uint raw) => (int)((raw >> 23) & MaximumB);
                internal static int DecodeBx(uint raw) => (int)((raw >> 14) & MaximumBx);
                internal static uint EncodeAbc(Lua51Opcode opcode, int a, int b, int c) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)c << 14) | ((uint)b << 23);
                internal static uint EncodeABx(Lua51Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)bx << 14);
            }
            """);
    }
}

[Generator]
public sealed class LuaVersionProfileGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor MissingChunkFormat = new(
        "LUNILGEN002",
        "Version adapter has no chunk format",
        "The enabled adapter symbol for '{0}' requires a LuaVersionProfile ChunkFormat declaration",
        "Lunil.Build",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!string.Equals(context.Compilation.AssemblyName, "Lunil.Core", StringComparison.Ordinal))
        {
            return;
        }

        var version = context.Compilation.GetTypeByMetadataName("Lunil.Core.LuaLanguageVersion");
        if (version is null || version.TypeKind != TypeKind.Enum)
        {
            return;
        }

        var profileAttribute = context.Compilation.GetTypeByMetadataName(
            "Lunil.Core.LuaVersionProfileAttribute");
        if (profileAttribute is null)
        {
            return;
        }

        var adapterSymbols = context.ParseOptions.PreprocessorSymbolNames;
        var values = version.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .OrderBy(static field => Convert.ToInt32(field.ConstantValue, CultureInfo.InvariantCulture))
            .Select(field =>
            {
                var attribute = field.GetAttributes().FirstOrDefault(candidate =>
                    SymbolEqualityComparer.Default.Equals(candidate.AttributeClass, profileAttribute));
                var synchronousFinalizerErrors = false;
                var supportsGenerationalCollection = false;
                var preservesDeadThreadOpenUpvalues = false;
                var cachesClosuresByUpvalues = false;
                var hasWarnLibrary = false;
                var hasCoroutineClose = false;
                var hasUtf8Library = false;
                var hasBit32Library = false;
                var hasRawLength = false;
                var hasGlobalUnpack = false;
                var hasLoadString = false;
                var hasModuleLibrary = false;
                var hasTableMove = false;
                var hasTablePack = false;
                var hasTableCreate = false;
                var hasStringPack = false;
                var hasStringGFind = false;
                var hasLegacyMath = false;
                var hasDebugSetCStackLimit = false;
                var hasPackageSearchers = false;
                var hasPackageLoaders = false;
                var hasPackageSeeAll = false;
                var hasLegacyTable = false;
                var chunkFormat = "LuaChunkFormat.None";
                if (attribute is not null)
                {
                    foreach (var named in attribute.NamedArguments)
                    {
                        if (named.Key == "ChunkFormat" && named.Value.Value is not null)
                        {
                            chunkFormat = Convert.ToInt32(
                                named.Value.Value,
                                CultureInfo.InvariantCulture) switch
                            {
                                1 => "LuaChunkFormat.Lua53",
                                2 => "LuaChunkFormat.Lua54",
                                3 => "LuaChunkFormat.Lua52",
                                4 => "LuaChunkFormat.Lua51",
                                5 => "LuaChunkFormat.Lua55",
                                _ => "LuaChunkFormat.None",
                            };
                        }
                        else if (named.Key == "SynchronousFinalizerErrors" &&
                            named.Value.Value is bool synchronous)
                        {
                            synchronousFinalizerErrors = synchronous;
                        }
                        else if (named.Key == "SupportsGenerationalCollection" &&
                            named.Value.Value is bool generational)
                        {
                            supportsGenerationalCollection = generational;
                        }
                        else if (named.Key == "PreservesDeadThreadOpenUpvalues" &&
                            named.Value.Value is bool preserves)
                        {
                            preservesDeadThreadOpenUpvalues = preserves;
                        }
                        else if (named.Key == "CachesClosuresByUpvalues" &&
                            named.Value.Value is bool caches)
                        {
                            cachesClosuresByUpvalues = caches;
                        }
                        else if (named.Key == "HasWarnLibrary" &&
                            named.Value.Value is bool hasWarn)
                        {
                            hasWarnLibrary = hasWarn;
                        }
                        else if (named.Key == "HasCoroutineClose" &&
                            named.Value.Value is bool hasClose)
                        {
                            hasCoroutineClose = hasClose;
                        }
                        else if (named.Key == "HasUtf8Library" && named.Value.Value is bool hasUtf8)
                        {
                            hasUtf8Library = hasUtf8;
                        }
                        else if (named.Key == "HasBit32Library" && named.Value.Value is bool hasBit32)
                        {
                            hasBit32Library = hasBit32;
                        }
                        else if (named.Key == "HasRawLength" && named.Value.Value is bool rawLength)
                        {
                            hasRawLength = rawLength;
                        }
                        else if (named.Key == "HasGlobalUnpack" && named.Value.Value is bool globalUnpack)
                        {
                            hasGlobalUnpack = globalUnpack;
                        }
                        else if (named.Key == "HasLoadString" && named.Value.Value is bool loadString)
                        {
                            hasLoadString = loadString;
                        }
                        else if (named.Key == "HasModuleLibrary" && named.Value.Value is bool moduleLibrary)
                        {
                            hasModuleLibrary = moduleLibrary;
                        }
                        else if (named.Key == "HasTableMove" && named.Value.Value is bool tableMove)
                        {
                            hasTableMove = tableMove;
                        }
                        else if (named.Key == "HasTablePack" && named.Value.Value is bool tablePack)
                        {
                            hasTablePack = tablePack;
                        }
                        else if (named.Key == "HasTableCreate" && named.Value.Value is bool tableCreate)
                        {
                            hasTableCreate = tableCreate;
                        }
                        else if (named.Key == "HasStringPack" && named.Value.Value is bool stringPack)
                        {
                            hasStringPack = stringPack;
                        }
                        else if (named.Key == "HasStringGFind" && named.Value.Value is bool stringGFind)
                        {
                            hasStringGFind = stringGFind;
                        }
                        else if (named.Key == "HasLegacyMath" && named.Value.Value is bool legacyMath)
                        {
                            hasLegacyMath = legacyMath;
                        }
                        else if (named.Key == "HasDebugSetCStackLimit" && named.Value.Value is bool debugSetCStackLimit)
                        {
                            hasDebugSetCStackLimit = debugSetCStackLimit;
                        }
                        else if (named.Key == "HasPackageSearchers" && named.Value.Value is bool packageSearchers)
                        {
                            hasPackageSearchers = packageSearchers;
                        }
                        else if (named.Key == "HasPackageLoaders" && named.Value.Value is bool packageLoaders)
                        {
                            hasPackageLoaders = packageLoaders;
                        }
                        else if (named.Key == "HasPackageSeeAll" && named.Value.Value is bool packageSeeAll)
                        {
                            hasPackageSeeAll = packageSeeAll;
                        }
                        else if (named.Key == "HasLegacyTable" && named.Value.Value is bool legacyTable)
                        {
                            hasLegacyTable = legacyTable;
                        }
                    }
                }

                return (
                    field.Name,
                    IsImplemented: adapterSymbols.Contains(
                        $"LUNIL_{field.Name.ToUpperInvariant()}_ADAPTER"),
                    ChunkFormat: chunkFormat,
                    SynchronousFinalizerErrors: synchronousFinalizerErrors,
                    SupportsGenerationalCollection: supportsGenerationalCollection,
                    PreservesDeadThreadOpenUpvalues: preservesDeadThreadOpenUpvalues,
                    CachesClosuresByUpvalues: cachesClosuresByUpvalues,
                    HasWarnLibrary: hasWarnLibrary,
                    HasCoroutineClose: hasCoroutineClose,
                    HasUtf8Library: hasUtf8Library,
                    HasBit32Library: hasBit32Library,
                    HasRawLength: hasRawLength,
                    HasGlobalUnpack: hasGlobalUnpack,
                    HasLoadString: hasLoadString,
                    HasModuleLibrary: hasModuleLibrary,
                    HasTableMove: hasTableMove,
                    HasTablePack: hasTablePack,
                    HasTableCreate: hasTableCreate,
                    HasStringPack: hasStringPack,
                    HasStringGFind: hasStringGFind,
                    HasLegacyMath: hasLegacyMath,
                    HasDebugSetCStackLimit: hasDebugSetCStackLimit,
                    HasPackageSearchers: hasPackageSearchers,
                    HasPackageLoaders: hasPackageLoaders,
                    HasPackageSeeAll: hasPackageSeeAll,
                    HasLegacyTable: hasLegacyTable);
            })
            .ToArray();
        if (values.Length == 0)
        {
            return;
        }

        foreach (var value in values)
        {
            if (value.IsImplemented && value.ChunkFormat == "LuaChunkFormat.None")
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MissingChunkFormat,
                    Location.None,
                    value.Name));
                return;
            }
        }

        var cases = string.Join(
            ",\n            ",
            values.Select(static value =>
                $"LuaLanguageVersion.{value.Name} => new LuaVersionFeatures(" +
                $"{value.IsImplemented.ToString().ToLowerInvariant()}, " +
                $"{value.ChunkFormat}, " +
                $"{value.SynchronousFinalizerErrors.ToString().ToLowerInvariant()}, " +
                $"{value.SupportsGenerationalCollection.ToString().ToLowerInvariant()}, " +
                $"{value.PreservesDeadThreadOpenUpvalues.ToString().ToLowerInvariant()}, " +
                        $"{value.CachesClosuresByUpvalues.ToString().ToLowerInvariant()}, " +
                        $"{value.HasWarnLibrary.ToString().ToLowerInvariant()}, " +
                        $"{value.HasCoroutineClose.ToString().ToLowerInvariant()}, " +
                        $"{value.HasUtf8Library.ToString().ToLowerInvariant()}, " +
                        $"{value.HasBit32Library.ToString().ToLowerInvariant()}, " +
                        $"{value.HasRawLength.ToString().ToLowerInvariant()}, " +
                        $"{value.HasGlobalUnpack.ToString().ToLowerInvariant()}, " +
                        $"{value.HasLoadString.ToString().ToLowerInvariant()}, " +
                        $"{value.HasModuleLibrary.ToString().ToLowerInvariant()}, " +
                        $"{value.HasTableMove.ToString().ToLowerInvariant()}, " +
                        $"{value.HasTablePack.ToString().ToLowerInvariant()}, " +
                        $"{value.HasTableCreate.ToString().ToLowerInvariant()}, " +
                        $"{value.HasStringPack.ToString().ToLowerInvariant()}, " +
                        $"{value.HasStringGFind.ToString().ToLowerInvariant()}, " +
                        $"{value.HasLegacyMath.ToString().ToLowerInvariant()}, " +
                        $"{value.HasDebugSetCStackLimit.ToString().ToLowerInvariant()}, " +
                        $"{value.HasPackageSearchers.ToString().ToLowerInvariant()}, " +
                        $"{value.HasPackageLoaders.ToString().ToLowerInvariant()}, " +
                        $"{value.HasPackageSeeAll.ToString().ToLowerInvariant()}, " +
                        $"{value.HasLegacyTable.ToString().ToLowerInvariant()})"));
        var source = $$"""
            // <auto-generated />
            namespace Lunil.Core;

            /// <summary>Generated feature contract for each supported Lua version.</summary>
            public readonly record struct LuaVersionFeatures(
                bool IsImplemented,
                LuaChunkFormat ChunkFormat,
                bool SynchronousFinalizerErrors,
                bool SupportsGenerationalCollection,
                bool PreservesDeadThreadOpenUpvalues,
                bool CachesClosuresByUpvalues,
                bool HasWarnLibrary,
                bool HasCoroutineClose,
                bool HasUtf8Library,
                bool HasBit32Library,
                bool HasRawLength,
                bool HasGlobalUnpack,
                bool HasLoadString,
                bool HasModuleLibrary,
                bool HasTableMove,
                bool HasTablePack,
                bool HasTableCreate,
                bool HasStringPack,
                bool HasStringGFind,
                bool HasLegacyMath,
                bool HasDebugSetCStackLimit,
                bool HasPackageSearchers,
                bool HasPackageLoaders,
                bool HasPackageSeeAll,
                bool HasLegacyTable);

            public static class LuaVersionFeatureTable
            {
                public static LuaVersionFeatures Get(LuaLanguageVersion version) => version switch
                {
                    {{cases}},
                    _ => throw new System.ArgumentOutOfRangeException(nameof(version), version,
                        "Unknown Lua language version."),
                };
            }
            """;
        context.AddSource("LuaVersionFeatures.g.cs", source);
    }
}

[Generator]
public sealed class Lua52OpcodeTableGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var opcode = context.Compilation.GetTypeByMetadataName("Lunil.IR.Lua52.Lua52Opcode");
        if (opcode is null || opcode.TypeKind != TypeKind.Enum)
        {
            return;
        }

        var values = opcode.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .Select(static field => (Name: field.Name, Value: Convert.ToInt32(
                field.ConstantValue,
                CultureInfo.InvariantCulture)))
            .OrderBy(static item => item.Value)
            .ToArray();
        if (values.Length == 0)
        {
            return;
        }

        var cases = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua52Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        var source = $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua52;

            internal static class Lua52GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};

                internal static bool IsDefined(Lua52Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }

                internal static string GetName(Lua52Opcode opcode) => (int)opcode switch
                {
                    {{cases}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }

            internal static class Lua52GeneratedInstructionCodec
            {
                internal const int MaximumA = 0xff;
                internal const int MaximumB = 0x1ff;
                internal const int MaximumC = 0x1ff;
                internal const int MaximumBx = 0x3ffff;
                internal const int MaximumAx = 0x3ffffff;
                internal const int SignedBxOffset = MaximumBx >> 1;

                internal static Lua52Opcode DecodeOpcode(uint raw) =>
                    (Lua52Opcode)(raw & 0x3f);

                internal static int DecodeA(uint raw) => (int)((raw >> 6) & MaximumA);
                internal static int DecodeC(uint raw) => (int)((raw >> 14) & MaximumC);
                internal static int DecodeB(uint raw) => (int)((raw >> 23) & MaximumB);
                internal static int DecodeBx(uint raw) => (int)((raw >> 14) & MaximumBx);
                internal static int DecodeAx(uint raw) => (int)((raw >> 6) & MaximumAx);

                internal static uint EncodeAbc(Lua52Opcode opcode, int a, int b, int c) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)c << 14) | ((uint)b << 23);

                internal static uint EncodeABx(Lua52Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)bx << 14);

                internal static uint EncodeAx(Lua52Opcode opcode, int ax) =>
                    (uint)opcode | ((uint)ax << 6);
            }
            """;
        context.AddSource("Lua52GeneratedOpcodeTable.g.cs", source);
    }
}

[Generator]
public sealed class Lua55OpcodeTableGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var opcode = context.Compilation.GetTypeByMetadataName("Lunil.IR.Lua55.Lua55Opcode");
        if (opcode is null || opcode.TypeKind != TypeKind.Enum)
        {
            return;
        }

        var values = opcode.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .Select(static field => (Name: field.Name, Value: Convert.ToInt32(
                field.ConstantValue,
                CultureInfo.InvariantCulture)))
            .OrderBy(static item => item.Value)
            .ToArray();
        if (values.Length == 0)
        {
            return;
        }

        for (var index = 0; index < values.Length; index++)
        {
            if (values[index].Value != index || values[index].Value > 0x7f)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "LUNILGEN004",
                        "Invalid Lua 5.5 opcode layout",
                        "Lua55Opcode values must be contiguous and fit in seven bits",
                        "Lunil.Build",
                        DiagnosticSeverity.Error,
                        isEnabledByDefault: true),
                    Location.None));
                return;
            }
        }

        var names = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua55Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        context.AddSource("Lua55GeneratedOpcodeTable.g.cs", $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua55;

            internal static class Lua55GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};
                internal static bool IsDefined(Lua55Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }
                internal static string GetName(Lua55Opcode opcode) => (int)opcode switch
                {
                    {{names}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }

            public static class Lua55GeneratedInstructionCodec
            {
                public const int MaximumA = 0xff;
                public const int MaximumB = 0xff;
                public const int MaximumC = 0xff;
                public const int MaximumBx = 0x1ffff;
                public const int MaximumAx = 0x1ffffff;
                public const int SignedBxOffset = MaximumBx >> 1;
                public const int SignedJumpOffset = MaximumAx >> 1;
                public static Lua55Opcode DecodeOpcode(uint raw) => (Lua55Opcode)(raw & 0x7f);
                public static int DecodeA(uint raw) => (int)((raw >> 7) & MaximumA);
                public static int DecodeB(uint raw) => (int)((raw >> 16) & MaximumB);
                public static int DecodeC(uint raw) => (int)((raw >> 24) & MaximumC);
                public static int DecodeVB(uint raw) => (int)((raw >> 16) & 0x3f);
                public static int DecodeVC(uint raw) => (int)((raw >> 22) & 0x3ff);
                public static bool DecodeK(uint raw) => ((raw >> 15) & 1) != 0;
                public static int DecodeBx(uint raw) => (int)((raw >> 15) & MaximumBx);
                public static int DecodeAx(uint raw) => (int)((raw >> 7) & MaximumAx);
                public static int DecodeSignedBx(uint raw) => DecodeBx(raw) - SignedBxOffset;
                public static int DecodeSignedJump(uint raw) => DecodeAx(raw) - SignedJumpOffset;
                public static uint EncodeAbc(Lua55Opcode opcode, int a, int b, int c, bool k = false) =>
                    (uint)opcode | ((uint)a << 7) | ((k ? 1u : 0u) << 15) |
                    ((uint)b << 16) | ((uint)c << 24);
                public static uint EncodeVAbc(Lua55Opcode opcode, int a, int vb, int vc, bool k = false) =>
                    (uint)opcode | ((uint)a << 7) | ((k ? 1u : 0u) << 15) |
                    ((uint)vb << 16) | ((uint)vc << 22);
                public static uint EncodeABx(Lua55Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 7) | ((uint)bx << 15);
                public static uint EncodeAx(Lua55Opcode opcode, int ax) =>
                    (uint)opcode | ((uint)ax << 7);
            }
            """);
    }
}
