using Microsoft.CodeAnalysis;

namespace Lunil.IR.Generators;

[Generator]
public sealed class Lua51OpcodeTableGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor InvalidOpcodeLayout = new(
        "LUNILGEN003",
        "Invalid Lua 5.1 opcode layout",
        "Lua51Opcode values must be contiguous from zero and fit the six-bit opcode field; " +
        "expected {0}, found {1} on '{2}'",
        "Lunil.Build",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context) { }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!OpcodeTableGeneratorHelpers.TryGetValidatedValues(
            context,
            "Lunil.IR.Lua51.Lua51Opcode",
            0x3f,
            InvalidOpcodeLayout,
            out var values))
        {
            return;
        }

        var names = string.Join(",\n            ", values.Select(static item => $"{item.Value} => nameof(Lua51Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        context.AddSource("Lua51GeneratedOpcodeTable.g.cs", $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua51;
            internal static class Lua51GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};
                internal static bool IsDefined(Lua51Opcode opcode) { var value = (int)opcode; return {{defined}}; }
                internal static string GetName(Lua51Opcode opcode) => (int)opcode switch
                {
                    {{names}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }
            internal static class Lua51GeneratedInstructionCodec
            {
                internal const int MaximumA = 0xff;
                internal const int MaximumB = 0x1ff;
                internal const int MaximumC = 0x1ff;
                internal const int MaximumBx = 0x3ffff;
                internal const int SignedBxOffset = MaximumBx >> 1;
                internal static Lua51Opcode DecodeOpcode(uint raw) => (Lua51Opcode)(raw & 0x3f);
                internal static int DecodeA(uint raw) => (int)((raw >> 6) & MaximumA);
                internal static int DecodeC(uint raw) => (int)((raw >> 14) & MaximumC);
                internal static int DecodeB(uint raw) => (int)((raw >> 23) & MaximumB);
                internal static int DecodeBx(uint raw) => (int)((raw >> 14) & MaximumBx);
                internal static uint EncodeAbc(Lua51Opcode opcode, int a, int b, int c) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)c << 14) | ((uint)b << 23);
                internal static uint EncodeABx(Lua51Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)bx << 14);
            }
            """);
    }
}
