using System.Globalization;
using Microsoft.CodeAnalysis;

namespace Lunil.IR.Generators;

[Generator]
public sealed class Lua53OpcodeTableGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        var opcode = context.Compilation.GetTypeByMetadataName("Lunil.IR.Lua53.Lua53Opcode");
        if (opcode is null || opcode.TypeKind != TypeKind.Enum)
        {
            return;
        }

        var values = opcode.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(static field => field.HasConstantValue)
            .Select(static field => (Name: field.Name, Value: Convert.ToInt32(
                field.ConstantValue,
                CultureInfo.InvariantCulture)))
            .OrderBy(static item => item.Value)
            .ToArray();
        if (values.Length == 0)
        {
            return;
        }

        var cases = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua53Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        var source = $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua53;

            internal static class Lua53GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};

                internal static bool IsDefined(Lua53Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }

                internal static string GetName(Lua53Opcode opcode) => (int)opcode switch
                {
                    {{cases}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }
            """;
        context.AddSource("Lua53GeneratedOpcodeTable.g.cs", source);
    }
}
