using Microsoft.CodeAnalysis;

namespace Lunil.IR.Generators;

[Generator]
public sealed class Lua52OpcodeTableGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor InvalidOpcodeLayout = new(
        "LUNILGEN005",
        "Invalid Lua 5.2 opcode layout",
        "Lua52Opcode values must be contiguous from zero and fit the six-bit opcode field; " +
        "expected {0}, found {1} on '{2}'",
        "Lunil.Build",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!OpcodeTableGeneratorHelpers.TryGetValidatedValues(
            context,
            "Lunil.IR.Lua52.Lua52Opcode",
            0x3f,
            InvalidOpcodeLayout,
            out var values))
        {
            return;
        }

        var cases = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua52Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        var source = $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua52;

            internal static class Lua52GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};

                internal static bool IsDefined(Lua52Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }

                internal static string GetName(Lua52Opcode opcode) => (int)opcode switch
                {
                    {{cases}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }

            internal static class Lua52GeneratedInstructionCodec
            {
                internal const int MaximumA = 0xff;
                internal const int MaximumB = 0x1ff;
                internal const int MaximumC = 0x1ff;
                internal const int MaximumBx = 0x3ffff;
                internal const int MaximumAx = 0x3ffffff;
                internal const int SignedBxOffset = MaximumBx >> 1;

                internal static Lua52Opcode DecodeOpcode(uint raw) =>
                    (Lua52Opcode)(raw & 0x3f);

                internal static int DecodeA(uint raw) => (int)((raw >> 6) & MaximumA);
                internal static int DecodeC(uint raw) => (int)((raw >> 14) & MaximumC);
                internal static int DecodeB(uint raw) => (int)((raw >> 23) & MaximumB);
                internal static int DecodeBx(uint raw) => (int)((raw >> 14) & MaximumBx);
                internal static int DecodeAx(uint raw) => (int)((raw >> 6) & MaximumAx);

                internal static uint EncodeAbc(Lua52Opcode opcode, int a, int b, int c) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)c << 14) | ((uint)b << 23);

                internal static uint EncodeABx(Lua52Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 6) | ((uint)bx << 14);

                internal static uint EncodeAx(Lua52Opcode opcode, int ax) =>
                    (uint)opcode | ((uint)ax << 6);
            }
            """;
        context.AddSource("Lua52GeneratedOpcodeTable.g.cs", source);
    }
}
