using Microsoft.CodeAnalysis;

namespace Lunil.IR.Generators;

[Generator]
public sealed class Lua55OpcodeTableGenerator : ISourceGenerator
{
    private static readonly DiagnosticDescriptor InvalidOpcodeLayout = new(
        "LUNILGEN004",
        "Invalid Lua 5.5 opcode layout",
        "Lua55Opcode values must be contiguous from zero and fit the seven-bit opcode field; " +
        "expected {0}, found {1} on '{2}'",
        "Lunil.Build",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(GeneratorInitializationContext context)
    {
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (!OpcodeTableGeneratorHelpers.TryGetValidatedValues(
            context,
            "Lunil.IR.Lua55.Lua55Opcode",
            0x7f,
            InvalidOpcodeLayout,
            out var values))
        {
            return;
        }

        var names = string.Join(",\n            ", values.Select(static item =>
            $"{item.Value} => nameof(Lua55Opcode.{item.Name})"));
        var defined = string.Join(" || ", values.Select(static item => $"value == {item.Value}"));
        context.AddSource("Lua55GeneratedOpcodeTable.g.cs", $$"""
            // <auto-generated />
            namespace Lunil.IR.Lua55;

            internal static class Lua55GeneratedOpcodeTable
            {
                internal const int Count = {{values.Length}};
                internal static bool IsDefined(Lua55Opcode opcode)
                {
                    var value = (int)opcode;
                    return {{defined}};
                }
                internal static string GetName(Lua55Opcode opcode) => (int)opcode switch
                {
                    {{names}},
                    _ => $"Unknown ({(int)opcode})",
                };
            }

            public static class Lua55GeneratedInstructionCodec
            {
                public const int MaximumA = 0xff;
                public const int MaximumB = 0xff;
                public const int MaximumC = 0xff;
                public const int MaximumBx = 0x1ffff;
                public const int MaximumAx = 0x1ffffff;
                public const int SignedBxOffset = MaximumBx >> 1;
                public const int SignedJumpOffset = MaximumAx >> 1;
                public static Lua55Opcode DecodeOpcode(uint raw) => (Lua55Opcode)(raw & 0x7f);
                public static int DecodeA(uint raw) => (int)((raw >> 7) & MaximumA);
                public static int DecodeB(uint raw) => (int)((raw >> 16) & MaximumB);
                public static int DecodeC(uint raw) => (int)((raw >> 24) & MaximumC);
                public static int DecodeVB(uint raw) => (int)((raw >> 16) & 0x3f);
                public static int DecodeVC(uint raw) => (int)((raw >> 22) & 0x3ff);
                public static bool DecodeK(uint raw) => ((raw >> 15) & 1) != 0;
                public static int DecodeBx(uint raw) => (int)((raw >> 15) & MaximumBx);
                public static int DecodeAx(uint raw) => (int)((raw >> 7) & MaximumAx);
                public static int DecodeSignedBx(uint raw) => DecodeBx(raw) - SignedBxOffset;
                public static int DecodeSignedJump(uint raw) => DecodeAx(raw) - SignedJumpOffset;
                public static uint EncodeAbc(Lua55Opcode opcode, int a, int b, int c, bool k = false) =>
                    (uint)opcode | ((uint)a << 7) | ((k ? 1u : 0u) << 15) |
                    ((uint)b << 16) | ((uint)c << 24);
                public static uint EncodeVAbc(Lua55Opcode opcode, int a, int vb, int vc, bool k = false) =>
                    (uint)opcode | ((uint)a << 7) | ((k ? 1u : 0u) << 15) |
                    ((uint)vb << 16) | ((uint)vc << 22);
                public static uint EncodeABx(Lua55Opcode opcode, int a, int bx) =>
                    (uint)opcode | ((uint)a << 7) | ((uint)bx << 15);
                public static uint EncodeAx(Lua55Opcode opcode, int ax) =>
                    (uint)opcode | ((uint)ax << 7);
            }
            """);
    }
}
