namespace Lunil.IR.Lua53;

public enum Lua53Opcode : byte
{
    Move = 0,
    LoadConstant = 1,
    LoadConstantExtra = 2,
    LoadBoolean = 3,
    LoadNil = 4,
    GetUpvalue = 5,
    GetGlobal = 6,
    GetTable = 7,
    SetTableUpvalue = 8,
    SetUpvalue = 9,
    SetTable = 10,
    NewTable = 11,
    Self = 12,
    Add = 13,
    Subtract = 14,
    Multiply = 15,
    Modulo = 16,
    Power = 17,
    Divide = 18,
    FloorDivide = 19,
    BitwiseAnd = 20,
    BitwiseOr = 21,
    BitwiseXor = 22,
    ShiftLeft = 23,
    ShiftRight = 24,
    UnaryMinus = 25,
    BitwiseNot = 26,
    LogicalNot = 27,
    Length = 28,
    Concatenate = 29,
    Jump = 30,
    Equal = 31,
    LessThan = 32,
    LessOrEqual = 33,
    Test = 34,
    TestSet = 35,
    Call = 36,
    TailCall = 37,
    Return = 38,
    NumericForLoop = 39,
    NumericForPrepare = 40,
    GenericForCall = 41,
    GenericForLoop = 42,
    SetList = 43,
    Closure = 44,
    VarArg = 45,
    ExtraArgument = 46,
}
