<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PublishAot Condition="'$(LunilNativeAotPublish)' == 'true'">true</PublishAot>
    <PublishReadyToRun Condition="'$(LunilReadyToRunPublish)' == 'true'">true</PublishReadyToRun>
    <SelfContained Condition="'$(LunilNativeAotPublish)' == 'true' Or '$(LunilReadyToRunPublish)' == 'true'">true</SelfContained>
    <PublishAot Condition="'$(PublishAot)' == ''">false</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <TrimMode>full</TrimMode>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL3050</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lunil.Hosting.Generators\Lunil.Hosting.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      GlobalPropertiesToRemove="PublishAot;PublishTrimmed;TrimMode;RuntimeIdentifier;SelfContained;LunilNativeAotPublish;LunilReadyToRunPublish" />
    <ProjectReference Include="..\..\src\Lunil.CodeGen.Cil\Lunil.CodeGen.Cil.csproj" />
    <ProjectReference Include="..\..\src\Lunil.Compiler\Lunil.Compiler.csproj" />
    <ProjectReference Include="..\..\src\Lunil.Hosting\Lunil.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Lunil.Workspace\Lunil.Workspace.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Modules\*.lua" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
