namespace Lunil.IR.Lua52;

public enum Lua52Opcode : byte
{
    Move = 0,
    LoadConstant = 1,
    LoadConstantExtra = 2,
    LoadBoolean = 3,
    LoadNil = 4,
    GetUpvalue = 5,
    GetTableUpvalue = 6,
    GetTable = 7,
    SetTableUpvalue = 8,
    SetUpvalue = 9,
    SetTable = 10,
    NewTable = 11,
    Self = 12,
    Add = 13,
    Subtract = 14,
    Multiply = 15,
    Divide = 16,
    Modulo = 17,
    Power = 18,
    UnaryMinus = 19,
    LogicalNot = 20,
    Length = 21,
    Concatenate = 22,
    Jump = 23,
    Equal = 24,
    LessThan = 25,
    LessOrEqual = 26,
    Test = 27,
    TestSet = 28,
    Call = 29,
    TailCall = 30,
    Return = 31,
    NumericForLoop = 32,
    NumericForPrepare = 33,
    GenericForCall = 34,
    GenericForLoop = 35,
    SetList = 36,
    Closure = 37,
    VarArg = 38,
    ExtraArgument = 39,
}
